### ISSUE TITLE
Refactor CasoDeUso5, CasoDeUso6,  CasoDeUso11. No se debe testear que un objeto sea de un tipo

### ISSUE THREAD

**Issue by RodriguezNazareno56** [RodriguezNazareno56/FIUBA-Algo3-TP2#18]
Mi corrector en el TP1 fue Joaquin Rivero, una de las correcciones que me hizo fue:

Pruebas: : REGULAR
[Medio] No se debe testear que un objeto sea de un tipo. Se debe testear comportamiento. Tampoco que un objeto sea nil

En los caso de uso 5, 6 y 11, hacemos:
`assertEquals(gladiador.getEquipamiento().getClass(), Llave.class);`

Si bien idealmente debería haber un refactor para quitar el `.getEquipamiento`. **Es importante cambiar este modo de validar, comparando tipos**.

**Comment by hmaldonado12** [comment]
Se resuleve el issue, agregando un atributo de inventario al gladiador y con esto probar el caso de uso de forma indirecta. Se modifica el nombre de IncrementarEquipo por EquipoIncrementado.
Tambien se agrega un metodo al gladiador que se llama recibirConsecuencia y el mismo resuelve segun la consecuencia.
