### ISSUE TITLE
Sobre inventarioDeEQuiapmiento en caso de Refactor para quitar el getEquipamiento() / obtenerEquipamiento()

### ISSUE THREAD

**Issue by RodriguezNazareno56** [RodriguezNazareno56/FIUBA-Algo3-TP2#24]
Abro este issue cómo discusión para que todos opinen, tengo dudas sobre lo siguiente:

Lo primero es que no termino de estar seguro de esta lógica de assertion en casos de uso como el 5

``` java
    @Test
    public void verificarQueSiRecibeUnPremioPorPrimeraVezObtieneUnCasco() {
        ....
       
        //Assert
        assertEquals(gladiador.obtenerEquipamiento(), inventarioDeEquipamiento.buscarPor(1));
```

No está abstraída de la implementación. Osea en verdad no estoy chequeando un comportamiento que está establecido por contrato, enunciado o caso de uso. Sino que estoy chequeando algo que se que va a ser así porque conozco la lógica interna de la clase. 
Chequear  que al decirle `gladiador.obtenerEquipamiento()`, tengo que obtener lo mismo que `inventarioDeEquipamiento.buscarPor(1)`, requiere saber cuánto mínimo saber que gladiador hace un `this.inventario.agregarSiNoExiste(equipamiento);`. También requiere conocer la lógica interna de `buscarPor(1)` cuando mínimo para saber qué buscarPor(1) retorna el Casco porque está implementado con un ArrayList<>() donde ya el lugar 0 está ocupado por `SinEquipamiento`.

Finalmente vale añadir que si deseamos deshacernos de getter innecesarios (aquellos utilizados sólo para testear) entonces seguiríamos en un problema al intentar quitar `gladiador.obtenerEquipamiento()`.

Una forma posible de testear estos casos, testeando consecuencias en el comportamientos y aprovechando que no se trata de un test unitario seria, ver que sucede si es atacado por un fiera ahora que posee un equipamiento superior

``` java
    @Test
    public void verificarQueSiRecibeUnPremioPorPrimeraVezObtieneUnCasco() {
        ....
       
        //Assert
        // un gladiador con casco pierde 15 puntos de energía frente al ataque de una fiera
        fiera.afectarGladiador(gladiador)
        assertEquals(gladiador.getEnergia(), 5);
```

Pero bueno, tampoco estoy tan seguro por eso lo abro como discusión

**Comment by RodriguezNazareno56** [comment]
El issue que genero la modificación primera fue este #18

**Comment by hmaldonado12** [comment]
Por eso lo0 comente en el grupo ya que la primera solucion me hacia ruido. Hice una segunda solucion que se ajusta mas a lo que estamos buscando

**Comment by fcondori10** [comment]
Es cierto que añade complejidad al incluir la clase inventario y ser necesario entender su dependencia con gladiador y los equipos. Es un requerimiento el que el primer premio sea un casco y otro requerimiento el que la fiera provoque perder 15 puntos de energía con el casco. Al ser requerimientos es más difícil que cambien, en cambio los refactor que hagamos nosotros sobre nuestras implementaciones pueden cambiar como en inventario.

Mejor testear sobre el comportamiento esperado si tiene el casco el cual resulta ser que los ataques con las fieras resultan ser de 15 o que al mejorarse recibieses una armadura

Si nos quisiéramos deshacer también del getEnergia propondría lo siguiente. Podemos inicializar al jugador con 15 de energía, premiarlo y afectarlo con la fiera, luego probar si puede avanzar. Como la fiera quita 15 puntos de energía el jugador no puede avanzar y lanza una excepción, la cual por ejemplo, usamos en el caso de uso 3



    @Test
    public void verificarQueSiRecibeUnPremioPorPrimeraVezObtieneUnCasco() {
       
       // un gladiador inicializado con 15 puntos de energía y premiado por primera vez

       fiera.afectarGladiador(gladiador)
       //Assert
       Throwable exception= Assertions.assertThrows(MovimientoExeption.class, () -> {
            this.gladiador.mover();
        }) 
Lo que sucede es que tambien deberiamos probar el caso contrario, en el que tiene 16 de energía al inicio y aún con el ataque de la fiera puede avanzar. De esta forma sabriamos que el gladiador tiene el casco pues aún con un ataque de 15 de energía el gladiador aún puede moverse debido a la resistencia del casco
Parece algo rebuscado, pero el ataque de la fiera es algo establecido por contrato

**Comment by Jmsosaa** [comment]
Comparto la forma de testear el caso de uso como menciono Gustavo. El gladiador se inicia con Energia = 20 y al obtener por primera vez Equipamiento, se le agrega el casco. 

Si es atacado por la fiera teniendo un casco, su energia disminuye a 15. Sabiendo que cada avance le cuesta al gladiador un punto de energia, podemos hacer que avace 5 veces para que agote toda su energia. 

Al intentar avanzar una 6ta vez verificamos que se lanze la exepcion "El gladiador no se puede mover sin energia".
