### ISSUE TITLE
implementaciones para Caso de uso 9

### ISSUE THREAD

**Issue by Jmsosaa** [RodriguezNazareno56/FIUBA-Algo3-TP2#41]
Para el caso de uso 9:
 
_"Verificar que si llega a la meta sin llave en el equipamiento, retrocede a la mitad de las casillas"_

Podriamos pensar que la ultima casilla tiene como consecuencia "Ganar". En caso que tenga la llave se arroja la exeption para despues tratarla y en caso que no tenga la llave regresa el jugador a la mitad del juego. 

Como las consecuencias las asignan con el JSON deberiamos ver si es posible asignarla nosotros.

**Comment by RodriguezNazareno56** [comment]
Implementado en el Pull Request: Aplicar consecuencias al mover para CasoDeUso9 #51
