### ISSUE TITLE
Comida comportamiento. Inconsistencia entre enunciado y caso de uso 4.

### ISSUE THREAD

**Issue by RodriguezNazareno56** [RodriguezNazareno56/FIUBA-Algo3-TP2#7]
El caso de uso 4 de la entrega 1 es
● Verificar que si recibe comida incrementa energía en 10

Por enunciado

| Premio | Qué sucede | Impacto             |
|--------|------------|---------------------|
| Comida | El jugador encuentra una comida (usen su creatividad) | La energía se ve incrementada en 15 puntos |

En la catedra respondieron:
```
Joaquin Gomez [hace 5 días]
tomen las que esten al principio, no en las pruebas. Si aparece otro caso, avisen por favor
```

Hay que:

- [ ] Cambiar el test casoDeUso4, tanto nombre como comportamiento esperado
- [ ] Cambiar el comportamiento de Comida, hoy devuelve un objeto Energia con valor 10, debe tener valor 15

**Comment by fcondori10** [comment]
Solucionado en pull request [#35](https://github.com/RodriguezNazareno56/FIUBA-Algo3-TP2/pull/35)
